# Generated by Django 6.1 on 2026-08-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_checkout_session_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payphone_authorization_code',
            field=models.CharField(blank=True, max_length=60, verbose_name='código de autorización'),
        ),
        migrations.AddField(
            model_name='order',
            name='payphone_client_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=60, unique=True, verbose_name='id de transacción (nuestro)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payphone_transaction_id',
            field=models.CharField(blank=True, max_length=60, verbose_name='id de transacción de PayPhone'),
        ),
    ]
