# Generated by Django 6.1 on 2026-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='banco')),
                ('account_type', models.CharField(blank=True, max_length=50, verbose_name='tipo de cuenta')),
                ('account_number', models.CharField(max_length=60, verbose_name='número de cuenta')),
                ('holder_name', models.CharField(max_length=120, verbose_name='a nombre de')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
                'ordering': ['order', 'bank_name'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='payphone_authorization_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payphone_client_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payphone_transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, upload_to='comprobantes/%Y/%m/', verbose_name='comprobante de pago'),
        ),
    ]
