# Generated by Django 6.1 on 2026-08-24 04:22

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_bankaccount_remove_order_payphone_authorization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.payment_proof_upload_to, verbose_name='comprobante de pago'),
        ),
    ]
