# Generated by Django 6.1 on 2026-08-22 03:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=120, verbose_name='nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(max_length=30, verbose_name='teléfono del cliente'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, verbose_name='vence'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('expired', 'Vencida'), ('converted', 'Convertida en pedido'), ('cancelled', 'Cancelada')], db_index=True, default='active', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.productvariant', verbose_name='variante'),
        ),
    ]
