# Generated by Django 6.1 on 2026-08-24 04:22

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.core.uploads.product_image_upload_to, verbose_name='imagen'),
        ),
    ]
